language: go
sudo: false
# The follow addons are a requirement for the pixel library
addons:
  apt:
    packages:
      - xorg-dev
      - libx11-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libopenal-dev
      - libasound2-dev
go:
  - tip
  - 1.12.x
  - 1.11.x

env:
  global:
    - GO111MODULE=on

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: true

script:
  - go test -v -cover -race ./...
